Guardian AI
GuardianUI/landing-page pull request #25
Opened 2023-02-25 07:54 UTC by TheErrrors

2023-02-25 16:04 UTC, ivelin requested changes
Looks good except for embedded svg data. Please use friendly named links to svg icons via local files or CDN urls.

2023-02-25 16:04 UTC, ivelin commented on ai.html
> +                                            d="M7 7C5.3 7 4 8.3 4 10L4 13L46 13L46 10C46 8.3 44.7 7 43 7L7 7 z M 8 9C8.552 9 9 9.448 9 10C9 10.552 8.552 11 8 11C7.448 11 7 10.552 7 10C7 9.448 7.448 9
This does not look great. Mixing binary data into source code.
Hard to maintain embedded binary data. Why not link to a local or CDN svg icon file with a recognizable name?

2023-02-26 04:36 UTC, lipmaneth commented
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNjRjMGJkYjQtZGQ1Mi00NjhmLThkMjQtMjk0MmE5ODMxZmM5IiwiZGVwbG95X2lkIjoiNjNmOWJlZDBkMzJlZDMwMDA4NTJmNmZhIiwiaWQiOiJhZDYyM2RhMi0xZTNiLTRjNTEtODU2My0xMzhjZmQ0ZDY1Y2YifQ==)

Also the "Model Training" section header and copy should be above the second image for mobile view. It is currently underneath the image. 
<details><summary>Browser metadata</summary>





```
Path:      /ai.html
Browser:   Chrome 109.0.0.0 on Mac OS 10.15.7
Viewport:  1166 x 978 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-25--lustrous-snickerdoodle-f0ebfa.netlify.app%2Fai.html&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=109.0&resolution=1166x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-25--lustrous-snickerdoodle-f0ebfa.netlify.app/ai.html) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63f9bed0d32ed3000852f6fa&commentID=63fae1e69a249e2322af93b2&resolution=resolved)

2023-02-28 16:04 UTC, ivelin commented
@lipmaneth let me know when you review this. I'll go next.

2023-02-28 16:21 UTC, merged