Update <head> to include more metadata
GuardianUI/landing-page pull request #4
Opened 2023-02-10 16:45 UTC by lipmaneth

@ivelin Currently, the website does not share a preview image nor does it contain metatags for SEO and google. This PR is intended to do the following:

- Add a preview image that's visible when shared on social or via SMS. See #3 for associated image.
- Add a title tag usable by Google shown in search results.
- Add a meta description usable by Google shown in search results.

The developer already had some basic metadata, which I did not delete. I am unsure if his code should remain or if any of it should be removed. I played it safe and left it.

2023-02-10 20:04 UTC, lipmaneth commented
deploy preview https://raw.githack.com/GuardianUI/landing-page/848635b95d74dc18aae844e7d0c8d50b32142e13/index.html

2023-02-10 21:47 UTC, ivelin requested changes
Nice work. See the duplicate tag comment.

2023-02-10 21:47 UTC, ivelin commented on index.html
>          <meta
Repetitive meta description. Drop one.

2023-02-13 15:39 UTC, ivelin approved these changes
well done

2023-02-13 15:39 UTC, merged